'use client'

import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, Check, CheckCircle2, ClipboardCheck, Clock3, LoaderCircle, Search, ShieldCheck, Snowflake, Sprout, X } from 'lucide-react'
import { supabase } from '../../../lib/supabase'
import type { SeasonOperationManualTaskKey, SeasonOperationTask, SeasonPhase } from '../../../lib/season-operations'

type Camper = { camperId: string, name: string, lotNumber: string, seasonYear: number, phase: SeasonPhase, completed: number, total: number, percent: number, ready: boolean, tasks: SeasonOperationTask[] }
type ResponseData = { generatedAt: string, year: number, phase: SeasonPhase, counts: { total: number, needingAction: number, ready: number, checksRemaining: number }, campers: Camper[] }
type Editor = { camper: Camper, task: SeasonOperationTask, taskKey: SeasonOperationManualTaskKey, completed: boolean }

export default function SeasonOperationsPage() {
  const now = new Date(), initialPhase: SeasonPhase = now.getMonth() >= 8 ? 'closing' : 'opening'
  const [year, setYear] = useState(now.getFullYear()), [phase, setPhase] = useState<SeasonPhase>(initialPhase)
  const [data, setData] = useState<ResponseData | null>(null), [loading, setLoading] = useState(true), [loadError, setLoadError] = useState(''), [message, setMessage] = useState('')
  const [search, setSearch] = useState(''), [filter, setFilter] = useState<'needs' | 'ready' | 'all'>('needs'), [expanded, setExpanded] = useState('')
  const [editor, setEditor] = useState<Editor | null>(null), [note, setNote] = useState(''), [saving, setSaving] = useState(false)
  useEffect(() => { void load() }, [year, phase])
  async function token() { const { data: session } = await supabase.auth.getSession(); return session.session?.access_token || '' }
  async function load() { setLoading(true); setLoadError(''); try { const access = await token(); if (!access) throw new Error('Your Admin login expired. Sign in again and retry.'); const response = await fetch(`/api/admin-season-operations?year=${year}&phase=${phase}`, { headers: { Authorization: `Bearer ${access}` }, cache: 'no-store' }); const result = await response.json().catch(() => ({})); if (!response.ok || !result.counts || !Array.isArray(result.campers)) throw new Error(result.error || 'Season operations could not be loaded.'); setData(result) } catch (error) { setLoadError(error instanceof Error ? error.message : 'Season operations could not be loaded.') } finally { setLoading(false) } }
  async function save() { if (!editor) return; setSaving(true); try { const access = await token(); if (!access) throw new Error('Your Admin login expired.'); const response = await fetch('/api/admin-season-operations', { method: 'POST', headers: { Authorization: `Bearer ${access}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ camperId: editor.camper.camperId, seasonYear: year, phase, taskKey: editor.taskKey, completed: editor.completed, note }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'The season task could not be saved.'); setMessage(`${editor.task.label} ${editor.completed ? 'confirmed' : 'reopened'} for ${editor.camper.name}.`); setEditor(null); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'The season task could not be saved.') } finally { setSaving(false) } }
  const visible = useMemo(() => (data?.campers || []).filter((camper) => { const term = search.trim().toLowerCase(); return (!term || `${camper.name} ${camper.lotNumber}`.toLowerCase().includes(term)) && (filter === 'all' || (filter === 'ready' ? camper.ready : !camper.ready)) }), [data, search, filter])
  if (loading && !data) return <main className="portal-loading"><LoaderCircle className="spin" /><h1>Verifying season operations…</h1></main>
  if (loadError) return <main className="portal-loading" role="alert"><AlertTriangle /><h1>Season operations are temporarily unavailable</h1><p>{loadError}</p><p>No incomplete item is being shown as complete.</p><button className="portal-loading-retry" onClick={load}>Try again</button></main>
  return <main className="admin-onboarding-page">
    <section className="admin-onboarding-hero"><div><small>{phase === 'opening' ? 'SEASON OPENING' : 'SEASON CLOSING'} · {year}</small><h1>{phase === 'opening' ? 'Ready for arrival' : 'Ready for winter'}</h1><p>One accountable campsite checklist. System facts come from billing, documents, meters, gate access, renewals, and maintenance; physical work requires staff confirmation.</p></div><span>{phase === 'opening' ? <Sprout size={26} /> : <Snowflake size={26} />}<strong>{data?.counts.checksRemaining || 0}</strong><small>checks left</small></span></section>
    <section className="admin-onboarding-counts"><article><small>Active sites</small><strong>{data?.counts.total || 0}</strong></article><article><small>Need action</small><strong>{data?.counts.needingAction || 0}</strong></article><article><small>Ready</small><strong>{data?.counts.ready || 0}</strong></article><article><small>Checks left</small><strong>{data?.counts.checksRemaining || 0}</strong></article></section>
    {message && <p className="admin-onboarding-message" role="status">{message}</p>}
    <section className="admin-onboarding-toolbar"><label><Search size={16} /><input aria-label="Search season operations" placeholder="Search camper or site…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><div role="group" aria-label="Season controls"><button className={phase === 'opening' ? 'active' : ''} onClick={() => setPhase('opening')}>Opening</button><button className={phase === 'closing' ? 'active' : ''} onClick={() => setPhase('closing')}>Closing</button><button onClick={() => setYear(year - 1)}>← {year - 1}</button><button className="active">{year}</button><button onClick={() => setYear(year + 1)}>{year + 1} →</button></div><div role="group" aria-label="Filter sites"><button className={filter === 'needs' ? 'active' : ''} onClick={() => setFilter('needs')}>Needs action</button><button className={filter === 'ready' ? 'active' : ''} onClick={() => setFilter('ready')}>Ready</button><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All sites</button></div></section>
    <section className="admin-onboarding-list">{visible.length === 0 ? <div className="admin-onboarding-empty"><CheckCircle2 /><h2>No sites match this view</h2><p>Try another filter or season.</p></div> : visible.map((camper) => <article key={camper.camperId} className={camper.ready ? 'ready' : ''}><header><div><span>{camper.ready ? <CheckCircle2 /> : <Clock3 />}</span><div><small>SITE {camper.lotNumber}</small><h2>{camper.name}</h2><p>{camper.completed} of {camper.total} checks complete</p></div></div><strong>{camper.percent}%</strong></header><div className="admin-onboarding-progress"><i style={{ width: `${camper.percent}%` }} /></div><div className="admin-onboarding-summary">{camper.tasks.map((task) => <span className={task.complete ? 'complete' : ''} key={task.key}>{task.complete ? <Check size={12} /> : null}</span>)}</div><button className="admin-onboarding-expand" onClick={() => setExpanded(expanded === camper.camperId ? '' : camper.camperId)}>{expanded === camper.camperId ? 'Hide checklist' : 'Open checklist'} <ArrowRight size={15} /></button>{expanded === camper.camperId && <div className="admin-onboarding-tasks">{camper.tasks.map((task) => <div key={task.key} className={task.complete ? 'complete' : ''}><span>{task.complete ? <CheckCircle2 /> : <Clock3 />}</span><div><strong>{task.label}</strong><small>{task.detail}</small></div><aside>{task.href && <a href={task.href}>Open record</a>}{task.manualKey && <button onClick={() => { setEditor({ camper, task, taskKey: task.manualKey!, completed: !task.complete }); setNote('') }}>{task.complete ? 'Reopen' : 'Confirm complete'}</button>}{task.alternateManualKey && <button onClick={() => { setEditor({ camper, task, taskKey: task.alternateManualKey!, completed: !task.complete }); setNote('') }}>{task.complete ? 'Require again' : 'Mark not required'}</button>}</aside></div>)}</div>}</article>)}</section>
    <p className="admin-onboarding-verified"><ShieldCheck size={15} /> Verified {data?.generatedAt ? new Date(data.generatedAt).toLocaleString() : 'just now'}. This view never closes billing, renewals, maintenance, or access records automatically.</p>
    {editor && <div className="admin-onboarding-modal-backdrop" role="dialog" aria-modal="true" aria-label="Confirm season task"><section className="admin-onboarding-modal"><header><div><small>{phase.toUpperCase()} · {year}</small><h2>{editor.completed ? 'Complete' : 'Reopen'} {editor.task.label}</h2><p>{editor.camper.name} · Site {editor.camper.lotNumber}</p></div><button aria-label="Close" onClick={() => setEditor(null)}><X /></button></header><label><span>Required staff note</span><textarea required maxLength={1000} rows={4} placeholder="What was checked, who handled it, or why an exception applies…" value={note} onChange={(event) => setNote(event.target.value)} /></label><p><ClipboardCheck size={15} /> Saves current state plus append-only history with your Admin identity.</p><footer><button onClick={() => setEditor(null)}>Cancel</button><button className="primary" onClick={save} disabled={saving || !note.trim()}>{saving ? <LoaderCircle className="spin" /> : <CheckCircle2 />}{saving ? 'Saving…' : 'Confirm and record'}</button></footer></section></div>}
  </main>
}
