-- Camper roster imported from Campers.pdf.
-- Only the site label and camper name columns are included.
-- No email, phone, vehicle, emergency, billing, or portal data is invented.

INSERT INTO public.campers (
  lot_number,
  first_name,
  last_name,
  role,
  active
)
SELECT
  roster.lot_number,
  roster.first_name,
  roster.last_name,
  'camper',
  true
FROM (
  VALUES
    ('F1', 'G.', 'Conaway'),
    ('F2', 'Gary', 'Johnson'),
    ('POINT', 'D.', 'Hanson'),
    ('1', 'C.', 'Cato'),
    ('2', 'R.', 'Fite'),
    ('3', 'M.', 'Dauderman'),
    ('4', 'T.', 'Dickerson'),
    ('5', 'R.', 'Gustafson'),
    ('6', 'J.', 'Plummer'),
    ('7', 'S.', 'Vogel'),
    ('8', 'A.', 'Ernst'),
    ('9', 'J.', 'Johnson'),
    ('10', 'B.', 'Hoff'),
    ('11', 'S.', 'Elliott'),
    ('12', 'A.', 'Scott'),
    ('13', 'G.', 'Scott'),
    ('14', 'P.', 'Horn'),
    ('15', 'J.', 'Starner'),
    ('16', 'M.', 'Bartz'),
    ('16A', 'J.', 'Strain'),
    ('17', 'S.', 'Porter'),
    ('17A', 'J.', 'Porter'),
    ('18', 'C.', 'Marshall'),
    ('19', 'K.', 'Graham'),
    ('20', 'C.', 'Marshall'),
    ('21', 'C.', 'Porter'),
    ('22', 'M.', 'Wade'),
    ('23', 'K.', 'Smith'),
    ('24', 'C.', 'Boyd'),
    ('25', 'J.', 'Heepke'),
    ('26', 'C.', 'Matesa'),
    ('27', 'C.', 'Hoormann'),
    ('28', 'M.', 'Finch'),
    ('29', 'P.', 'Devening'),
    ('30', 'T.', 'Haugen'),
    ('31', 'D.', 'Beck'),
    ('32', 'T.', 'Crawford'),
    ('33', 'J.', 'Andrews'),
    ('34', 'J.', 'Cox'),
    ('35', 'R.', 'Vanetta'),
    ('35A', 'M.', 'Ballard'),
    ('35B', 'J.', 'Slemer'),
    ('36', 'S.', 'Norton'),
    ('37', 'K.', 'Seacrest'),
    ('39', 'Max', 'James'),
    ('40', 'R.', 'Benham'),
    ('41', 'M.', 'Hasson'),
    ('42', 'M.', 'Alfaro'),
    ('43', 'S.', 'Slayton'),
    ('44', 'J.', 'Marshall Jr.'),
    ('46', 'K.', 'Holmann'),
    ('47', 'C.', 'Kimball'),
    ('47A', 'Jason', 'Imel'),
    ('47B', 'J.', 'McNaughton'),
    ('47C', 'J.', 'Main'),
    ('48', 'A.', 'Finley'),
    ('48A', 'R.', 'Loomis'),
    ('48B', 'B.', 'Slemer'),
    ('48C', 'K.', 'Scott'),
    ('49', 'T.', 'Yount'),
    ('49A', 'C.', 'Horn'),
    ('50', 'J.', 'Giddings'),
    ('51', 'J.', 'Frost'),
    ('52', 'F.', 'Horat'),
    ('53', 'N.', 'Gonzales'),
    ('54', 'J.', 'Martin'),
    ('55', 'C.', 'Brinson'),
    ('56', 'M.', 'Logan'),
    ('57', 'M.', 'Brooksher'),
    ('FF1A', 'A.', 'Taylor'),
    ('FF1', 'S.', 'Yerkes'),
    ('FF2', 'B.', 'Trader'),
    ('FF3', 'D.', 'Weyhaupt'),
    ('FF4', 'R.', 'Burkhardt'),
    ('FF5', 'C.', 'Campbell'),
    ('FF6', 'W.', 'Click'),
    ('FF7', 'J.', 'Dipaolo'),
    ('FF8', 'D.', 'Greenwell'),
    ('FF9', 'G.', 'Cameron'),
    ('FF10', 'S.', 'Davis'),
    ('FF11', 'C.', 'Carter'),
    ('FF12', 'D.', 'Bohnensthil'),
    ('FF13', 'K.', 'Mcnish'),
    ('FF14', 'C.', 'Garibaldi'),
    ('FF15', 'D.', 'Trader'),
    ('FF15A', 'Jimmy', 'Smith'),
    ('FF16A', 'James', 'Marshall Jr.'),
    ('FF16', 'D.', 'Schaar'),
    ('FF17', 'P.', 'Quinn'),
    ('FF18', 'D.', 'Minert')
) AS roster(lot_number, first_name, last_name)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.campers existing
  WHERE UPPER(existing.lot_number::text) = UPPER(roster.lot_number)
);
