import { ArrowRight, ClipboardCheck, Mail, Phone, ShieldCheck, Trees } from 'lucide-react'
import { PageHero, PublicShell } from '../../components/PublicSite'
import WaitlistInterestForm from './WaitlistInterestForm'
import { publicPageMetadata } from '../../lib/publicMetadata'

export const metadata = publicPageMetadata('Join the Seasonal Site Interest List', 'Request seasonal membership information, share your camper details, and join the Bur Oaks future site availability list.', '/availability')

export default function AvailabilityPage() {
  return <PublicShell><main><PageHero eyebrow="Seasonal site interest list" title="Start the conversation for a future Bur Oaks site." description="Tell us what you are looking for, and we will keep your information ready when the right seasonal opportunity makes sense." />
    <section id="page-content" className="public-availability public-section"><div><span className="public-kicker">Seasonal membership</span><h2>Your weekends could look different.</h2><p>Bur Oaks offers annual site rentals within a private, gated community. Availability changes through the season, and the best next step is to share your camping setup so the office can match serious inquiries with the right future openings.</p><div className="public-process"><span><b>01</b><strong>Join the interest list</strong><small>Tell us what you are looking for.</small></span><span><b>02</b><strong>Plan a visit</strong><small>Walk the campground and see the community.</small></span><span><b>03</b><strong>Review the right fit</strong><small>If an opening matches, we will talk through next steps.</small></span></div></div><aside><Trees /><span>Limited seasonal sites</span><h3>Private community, thoughtful fit.</h3><p>Our team will review your information, keep it in the office waitlist, and contact you when a tour or site conversation makes sense.</p><a href="#membership-inquiry"><ClipboardCheck size={17} /> Join interest list</a><a href="tel:6184887927"><Phone size={17} /> Call 618-488-7927</a><a href="mailto:buroakscampground@gmail.com?subject=Seasonal%20Site%20Availability"><Mail size={17} /> Email about availability</a></aside></section>
    <section className="public-section public-waitlist-section"><div><span className="public-kicker"><ShieldCheck size={15} /> Future availability</span><h2>Request seasonal membership information.</h2><p>Fill this out once and your information goes straight to the Bur Oaks office waitlist. It helps us understand your camper, timing, and what kind of seasonal site would make sense.</p><ul className="public-waitlist-points"><li>Private gated seasonal community</li><li>Annual sites are limited and matched thoughtfully</li><li>Your inquiry goes directly into the office portal</li></ul></div><WaitlistInterestForm /></section>
    <section className="public-cta"><div><span className="public-kicker">Already a camper?</span><h2>Your campground account is one click away.</h2></div><div><a href="/login">Open camper portal <ArrowRight size={17} /></a></div></section>
  </main></PublicShell>
}
